import type {
  User,
  Pet,
  Veterinarian,
  Appointment,
  Medicine,
  Branch,
  Invoice,
  Referral,
  MedicalRecord,
  VaccinationSchedule,
  StockEntry,
} from './types'

export const branches: Branch[] = [
  { id: 'b1', name: 'Downtown Clinic', address: '123 Main St', phone: '555-0101', managerId: 'm1' },
  { id: 'b2', name: 'Westside Animal Hospital', address: '456 Oak Ave', phone: '555-0102', managerId: 'm2' },
  { id: 'b3', name: 'Northgate Pet Care', address: '789 Pine Blvd', phone: '555-0103', managerId: 'm3' },
]

export const users: User[] = [
  { id: 'o1', name: 'Sarah Johnson', email: 'sarah@email.com', role: 'owner', avatar: '/avatars/owner1.jpg' },
  { id: 'o2', name: 'Michael Chen', email: 'michael@email.com', role: 'owner', avatar: '/avatars/owner2.jpg' },
  { id: 'v1', name: 'Dr. Emily Wilson', email: 'emily@vetcare.com', role: 'vet', branchId: 'b1', avatar: '/avatars/vet1.jpg' },
  { id: 'v2', name: 'Dr. James Rodriguez', email: 'james@vetcare.com', role: 'vet', branchId: 'b2', avatar: '/avatars/vet2.jpg' },
  { id: 'm1', name: 'Lisa Thompson', email: 'lisa@vetcare.com', role: 'manager', branchId: 'b1', avatar: '/avatars/manager1.jpg' },
]

export const pets: Pet[] = [
  {
    id: 'p1',
    name: 'Buddy',
    species: 'dog',
    breed: 'Golden Retriever',
    age: 5,
    weight: 32,
    ownerId: 'o1',
    ownerName: 'Sarah Johnson',
    allergies: ['Chicken', 'Penicillin'],
    medicalAlerts: ['Hip dysplasia - monitor activity'],
    imageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=300&h=300&fit=crop',
    vaccinationStatus: 'up-to-date',
    lastVisit: '2024-02-15',
  },
  {
    id: 'p2',
    name: 'Luna',
    species: 'cat',
    breed: 'Siamese',
    age: 3,
    weight: 4.5,
    ownerId: 'o1',
    ownerName: 'Sarah Johnson',
    allergies: [],
    medicalAlerts: [],
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=300&h=300&fit=crop',
    vaccinationStatus: 'due-soon',
    lastVisit: '2024-01-20',
  },
  {
    id: 'p3',
    name: 'Max',
    species: 'dog',
    breed: 'German Shepherd',
    age: 7,
    weight: 40,
    ownerId: 'o2',
    ownerName: 'Michael Chen',
    allergies: ['Beef'],
    medicalAlerts: ['Arthritis - requires medication', 'Sensitive stomach'],
    imageUrl: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=300&h=300&fit=crop',
    vaccinationStatus: 'overdue',
    lastVisit: '2023-11-10',
  },
  {
    id: 'p4',
    name: 'Whiskers',
    species: 'cat',
    breed: 'Maine Coon',
    age: 2,
    weight: 6,
    ownerId: 'o2',
    ownerName: 'Michael Chen',
    allergies: ['Dairy'],
    medicalAlerts: [],
    imageUrl: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=300&h=300&fit=crop',
    vaccinationStatus: 'up-to-date',
    lastVisit: '2024-02-28',
  },
]

export const veterinarians: Veterinarian[] = [
  { id: 'v1', name: 'Dr. Emily Wilson', specialization: 'General Practice', branchId: 'b1', branchName: 'Downtown Clinic', rating: 4.9, available: true },
  { id: 'v2', name: 'Dr. James Rodriguez', specialization: 'Surgery', branchId: 'b2', branchName: 'Westside Animal Hospital', rating: 4.8, available: true },
  { id: 'v3', name: 'Dr. Sarah Kim', specialization: 'Dermatology', branchId: 'b1', branchName: 'Downtown Clinic', rating: 4.7, available: false },
  { id: 'v4', name: 'Dr. David Brown', specialization: 'Cardiology', branchId: 'b3', branchName: 'Northgate Pet Care', rating: 4.9, available: true },
  { id: 'v5', name: 'Dr. Maria Garcia', specialization: 'Oncology', branchId: 'b2', branchName: 'Westside Animal Hospital', rating: 4.6, available: true },
]

export const appointments: Appointment[] = [
  {
    id: 'a1',
    petId: 'p1',
    petName: 'Buddy',
    petSpecies: 'dog',
    ownerId: 'o1',
    ownerName: 'Sarah Johnson',
    vetId: 'v1',
    vetName: 'Dr. Emily Wilson',
    branchId: 'b1',
    branchName: 'Downtown Clinic',
    date: '2024-03-20',
    time: '09:00',
    type: 'checkup',
    status: 'scheduled',
  },
  {
    id: 'a2',
    petId: 'p2',
    petName: 'Luna',
    petSpecies: 'cat',
    ownerId: 'o1',
    ownerName: 'Sarah Johnson',
    vetId: 'v1',
    vetName: 'Dr. Emily Wilson',
    branchId: 'b1',
    branchName: 'Downtown Clinic',
    date: '2024-03-20',
    time: '10:30',
    type: 'vaccination',
    status: 'scheduled',
  },
  {
    id: 'a3',
    petId: 'p3',
    petName: 'Max',
    petSpecies: 'dog',
    ownerId: 'o2',
    ownerName: 'Michael Chen',
    vetId: 'v2',
    vetName: 'Dr. James Rodriguez',
    branchId: 'b2',
    branchName: 'Westside Animal Hospital',
    date: '2024-03-20',
    time: '14:00',
    type: 'followup',
    status: 'in-progress',
    notes: 'Follow-up for arthritis treatment',
  },
  {
    id: 'a4',
    petId: 'p4',
    petName: 'Whiskers',
    petSpecies: 'cat',
    ownerId: 'o2',
    ownerName: 'Michael Chen',
    vetId: 'v3',
    vetName: 'Dr. Sarah Kim',
    branchId: 'b1',
    branchName: 'Downtown Clinic',
    date: '2024-03-21',
    time: '11:00',
    type: 'checkup',
    status: 'scheduled',
  },
]

export const medicines: Medicine[] = [
  { id: 'm1', name: 'Amoxicillin 500mg', category: 'medicine', unit: 'tablets', currentStock: 150, minStock: 50, maxStock: 300, price: 0.50, branchId: 'b1' },
  { id: 'm2', name: 'Rabies Vaccine', category: 'vaccine', unit: 'doses', currentStock: 25, minStock: 20, maxStock: 100, price: 25.00, branchId: 'b1' },
  { id: 'm3', name: 'DHPP Vaccine', category: 'vaccine', unit: 'doses', currentStock: 8, minStock: 15, maxStock: 80, price: 30.00, branchId: 'b1' },
  { id: 'm4', name: 'Feline Distemper Vaccine', category: 'vaccine', unit: 'doses', currentStock: 45, minStock: 20, maxStock: 100, price: 28.00, branchId: 'b1' },
  { id: 'm5', name: 'Carprofen 75mg', category: 'medicine', unit: 'tablets', currentStock: 200, minStock: 100, maxStock: 500, price: 1.20, branchId: 'b1' },
  { id: 'm6', name: 'Metronidazole 250mg', category: 'medicine', unit: 'tablets', currentStock: 30, minStock: 50, maxStock: 200, price: 0.75, branchId: 'b1' },
  { id: 'm7', name: 'Omega-3 Fish Oil', category: 'supplement', unit: 'capsules', currentStock: 500, minStock: 100, maxStock: 1000, price: 0.30, branchId: 'b1' },
  { id: 'm8', name: 'Bordetella Vaccine', category: 'vaccine', unit: 'doses', currentStock: 12, minStock: 15, maxStock: 60, price: 22.00, branchId: 'b1' },
]

export const invoices: Invoice[] = [
  {
    id: 'inv1',
    appointmentId: 'a1',
    petName: 'Buddy',
    ownerName: 'Sarah Johnson',
    date: '2024-03-15',
    items: [
      { description: 'General Checkup', quantity: 1, unitPrice: 75.00, total: 75.00 },
      { description: 'Blood Test', quantity: 1, unitPrice: 45.00, total: 45.00 },
    ],
    total: 120.00,
    status: 'paid',
  },
  {
    id: 'inv2',
    appointmentId: 'a2',
    petName: 'Luna',
    ownerName: 'Sarah Johnson',
    date: '2024-03-18',
    items: [
      { description: 'Vaccination - Feline Distemper', quantity: 1, unitPrice: 28.00, total: 28.00 },
      { description: 'Office Visit', quantity: 1, unitPrice: 35.00, total: 35.00 },
    ],
    total: 63.00,
    status: 'pending',
  },
  {
    id: 'inv3',
    appointmentId: 'a3',
    petName: 'Max',
    ownerName: 'Michael Chen',
    date: '2024-02-28',
    items: [
      { description: 'Surgery Consultation', quantity: 1, unitPrice: 150.00, total: 150.00 },
      { description: 'X-Ray', quantity: 2, unitPrice: 85.00, total: 170.00 },
      { description: 'Pain Medication', quantity: 30, unitPrice: 1.20, total: 36.00 },
    ],
    total: 356.00,
    status: 'overdue',
  },
]

export const referrals: Referral[] = [
  {
    id: 'r1',
    fromVetId: 'v1',
    fromVetName: 'Dr. Emily Wilson',
    toVetId: 'v4',
    toVetName: 'Dr. David Brown',
    toBranchId: 'b3',
    toBranchName: 'Northgate Pet Care',
    petId: 'p1',
    petName: 'Buddy',
    reason: 'Heart murmur detected, needs cardiac evaluation',
    date: '2024-03-15',
    status: 'pending',
  },
  {
    id: 'r2',
    fromVetId: 'v2',
    fromVetName: 'Dr. James Rodriguez',
    toVetId: 'v3',
    toVetName: 'Dr. Sarah Kim',
    toBranchId: 'b1',
    toBranchName: 'Downtown Clinic',
    petId: 'p3',
    petName: 'Max',
    reason: 'Persistent skin condition requiring dermatology specialist',
    date: '2024-03-10',
    status: 'accepted',
  },
]

export const medicalRecords: MedicalRecord[] = [
  {
    id: 'mr1',
    petId: 'p1',
    petName: 'Buddy',
    vetId: 'v1',
    vetName: 'Dr. Emily Wilson',
    date: '2024-02-15',
    diagnosis: 'Annual wellness check - healthy',
    treatment: 'Routine examination, vaccinations updated',
    prescriptions: [
      { id: 'rx1', medicineId: 'm7', medicineName: 'Omega-3 Fish Oil', dosage: '1 capsule', frequency: 'daily', duration: '30 days', quantity: 30 },
    ],
    notes: 'Weight stable, coat healthy. Continue current diet. Heart murmur detected - referred to cardiologist.',
  },
  {
    id: 'mr2',
    petId: 'p3',
    petName: 'Max',
    vetId: 'v2',
    vetName: 'Dr. James Rodriguez',
    date: '2023-11-10',
    diagnosis: 'Arthritis flare-up in hind legs',
    treatment: 'Anti-inflammatory medication prescribed, physical therapy recommended',
    prescriptions: [
      { id: 'rx2', medicineId: 'm5', medicineName: 'Carprofen 75mg', dosage: '1 tablet', frequency: 'twice daily', duration: '14 days', quantity: 28 },
    ],
    notes: 'Owner reports difficulty climbing stairs. X-rays show moderate joint degeneration. Follow-up in 2 weeks.',
  },
]

export const vaccinationSchedules: VaccinationSchedule[] = [
  { id: 'vs1', petId: 'p1', petName: 'Buddy', vaccineId: 'm2', vaccineName: 'Rabies Vaccine', dueDate: '2024-08-15', status: 'scheduled' },
  { id: 'vs2', petId: 'p2', petName: 'Luna', vaccineId: 'm4', vaccineName: 'Feline Distemper Vaccine', dueDate: '2024-03-25', status: 'scheduled' },
  { id: 'vs3', petId: 'p3', petName: 'Max', vaccineId: 'm3', vaccineName: 'DHPP Vaccine', dueDate: '2024-02-01', status: 'overdue' },
  { id: 'vs4', petId: 'p4', petName: 'Whiskers', vaccineId: 'm2', vaccineName: 'Rabies Vaccine', dueDate: '2024-09-10', status: 'scheduled' },
  { id: 'vs5', petId: 'p1', petName: 'Buddy', vaccineId: 'm8', vaccineName: 'Bordetella Vaccine', dueDate: '2024-03-01', status: 'overdue' },
]

export const stockEntries: StockEntry[] = [
  { id: 'se1', medicineId: 'm1', medicineName: 'Amoxicillin 500mg', quantity: 100, type: 'add', date: '2024-03-01', userId: 'm1' },
  { id: 'se2', medicineId: 'm3', medicineName: 'DHPP Vaccine', quantity: 5, type: 'waste', reason: 'Expired', date: '2024-03-10', userId: 'm1' },
  { id: 'se3', medicineId: 'm6', medicineName: 'Metronidazole 250mg', quantity: 50, type: 'add', date: '2024-03-15', userId: 'm1' },
]

export const dashboardStats = {
  owner: {
    totalPets: 2,
    upcomingAppointments: 2,
    overdueVaccinations: 0,
    pendingInvoices: 1,
  },
  vet: {
    todayAppointments: 4,
    patientsThisWeek: 18,
    pendingReferrals: 2,
    completedToday: 2,
  },
  manager: {
    totalInventoryItems: 8,
    lowStockItems: 3,
    pendingInvoices: 2,
    monthlyRevenue: 4250.00,
    overdueVaccinations: 2,
  },
}
